// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

// const SUPABASE_URL = "https://slqptakhvjoykrnjyvvi.supabase.co";
// const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNscXB0YWtodmpveWtybmp5dnZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2MDE2NDcsImV4cCI6MjA2NDE3NzY0N30.WcpbL5_U5tkL9DWAkON2OUbABv-ga6pvrMcM_BQARcQ";

const SUPABASE_URL = "https://studio.ailacode.com";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.ewogICJyb2xlIjogImFub24iLAogICJpc3MiOiAic3VwYWJhc2UiLAogICJpYXQiOiAxNzMyOTM1NjAwLAogICJleHAiOiAxODkwNzAyMDAwCn0.mEgcsXnQ9d62vigQiABhN8ewO0wJAW0ulnAGkclkumw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY
);
